#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -e "/etc/init/nova-cert.conf" ]; then
	invoke-rc.d nova-cert start || true
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f nova-cert remove >/dev/null || true
# End automatically added section
