#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/nova-scheduler" ] && [ ! -L "/etc/init.d/nova-scheduler" ]; then
		if [ "`md5sum \"/etc/init.d/nova-scheduler\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' nova-scheduler | sed -n -e \"\\\\' /etc/init.d/nova-scheduler '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/nova-scheduler has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/nova-scheduler" "/etc/init.d/nova-scheduler.dpkg-bak"
		else
			rm -f "/etc/init.d/nova-scheduler"
		fi
	fi
fi
# End automatically added section
