#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -e "/etc/init/nova-consoleauth.conf" ]; then
	invoke-rc.d nova-consoleauth start || true
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f nova-consoleauth remove >/dev/null || true
# End automatically added section
