#!/bin/sh -e

if [ "$1" = "configure" ]; then
  chown root:root /etc/nova/rootwrap.d/network.filters
fi

# Automatically added by dh_installinit
if [ -e "/etc/init/nova-network.conf" ]; then
	invoke-rc.d nova-network start || true
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f nova-network remove >/dev/null || true
# End automatically added section

