#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/nova-network" ] && [ ! -L "/etc/init.d/nova-network" ]; then
		if [ "`md5sum \"/etc/init.d/nova-network\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' nova-network | sed -n -e \"\\\\' /etc/init.d/nova-network '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/nova-network has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/nova-network" "/etc/init.d/nova-network.dpkg-bak"
		else
			rm -f "/etc/init.d/nova-network"
		fi
	fi
fi
# End automatically added section
