#!/bin/sh -e

if [ "$1" = purge ]; then
	update-rc.d nova-xvpvncproxy remove
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d nova-xvpvncproxy remove >/dev/null
fi
# End automatically added section

