#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/nova-xcp-network" ]; then
	invoke-rc.d nova-xcp-network stop || true
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p nova-xcp-network 
else
	dpkg -L nova-xcp-network | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
