#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	if ! [ -e /etc/xcp/xenhost.conf ] ; then
		echo "{}" >/etc/xcp/xenhost.conf
	fi
fi


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p nova-xcp-plugins /usr/lib/xcp
fi

# End automatically added section


exit 0
