#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -e "/etc/init/nova-novncproxy.conf" ]; then
	invoke-rc.d nova-novncproxy start || true
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f nova-novncproxy remove >/dev/null || true
# End automatically added section
