#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/nova-novncproxy" ] && [ ! -L "/etc/init.d/nova-novncproxy" ]; then
		if [ "`md5sum \"/etc/init.d/nova-novncproxy\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' nova-novncproxy | sed -n -e \"\\\\' /etc/init.d/nova-novncproxy '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/nova-novncproxy has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/nova-novncproxy" "/etc/init.d/nova-novncproxy.dpkg-bak"
		else
			rm -f "/etc/init.d/nova-novncproxy"
		fi
	fi
fi
# End automatically added section
