#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/nova-api" ] && [ ! -L "/etc/init.d/nova-api" ]; then
		if [ "`md5sum \"/etc/init.d/nova-api\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' nova-api | sed -n -e \"\\\\' /etc/init.d/nova-api '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/nova-api has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/nova-api" "/etc/init.d/nova-api.dpkg-bak"
		else
			rm -f "/etc/init.d/nova-api"
		fi
	fi
fi
# End automatically added section
