#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/nova-api-os-volume" ] && [ ! -L "/etc/init.d/nova-api-os-volume" ]; then
		if [ "`md5sum \"/etc/init.d/nova-api-os-volume\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' nova-api-os-volume | sed -n -e \"\\\\' /etc/init.d/nova-api-os-volume '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/nova-api-os-volume has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/nova-api-os-volume" "/etc/init.d/nova-api-os-volume.dpkg-bak"
		else
			rm -f "/etc/init.d/nova-api-os-volume"
		fi
	fi
fi
# End automatically added section
