#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -e "/etc/init/nova-api-ec2.conf" ]; then
	invoke-rc.d nova-api-ec2 start || true
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f nova-api-ec2 remove >/dev/null || true
# End automatically added section
