#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/nova-api-ec2" ] && [ ! -L "/etc/init.d/nova-api-ec2" ]; then
		if [ "`md5sum \"/etc/init.d/nova-api-ec2\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' nova-api-ec2 | sed -n -e \"\\\\' /etc/init.d/nova-api-ec2 '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/nova-api-ec2 has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/nova-api-ec2" "/etc/init.d/nova-api-ec2.dpkg-bak"
		else
			rm -f "/etc/init.d/nova-api-ec2"
		fi
	fi
fi
# End automatically added section
