#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/nova-api-metadata" ] && [ ! -L "/etc/init.d/nova-api-metadata" ]; then
		if [ "`md5sum \"/etc/init.d/nova-api-metadata\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' nova-api-metadata | sed -n -e \"\\\\' /etc/init.d/nova-api-metadata '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/nova-api-metadata has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/nova-api-metadata" "/etc/init.d/nova-api-metadata.dpkg-bak"
		else
			rm -f "/etc/init.d/nova-api-metadata"
		fi
	fi
fi
# End automatically added section
