#!/bin/sh -e

if [ "$1" = "configure" ]; then
    if ! getent group libvirtd | grep -qE '\<nova\>'
    then
        adduser nova libvirtd
    fi
    chown root:root /etc/nova/rootwrap.d/compute.filters
fi

# Automatically added by dh_installinit
if [ -e "/etc/init/nova-compute.conf" ]; then
	invoke-rc.d nova-compute start || true
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f nova-compute remove >/dev/null || true
# End automatically added section

